SET FOREIGN_KEY_CHECKS=0;
-- --------------------------------------------------------

ALTER TABLE `@prefix@tab_inventaire` CHANGE `actif` `actif` INT(2) NOT NULL DEFAULT '1';

INSERT INTO `@prefix@tab_mode` (`code`, `label`, `date`) VALUES ('old-gods', 'old-gods', NOW());

SELECT @old_gods_id = a.`id`
  FROM `@prefix@tab_mode` a
  WHERE 1=1
  AND a.`code` = 'old-gods'
;

INSERT INTO `how-tab_inventaire`(`data_creation`, `nom`, `id_link`, `qualite`, `race`, `classe`, `cout`, `attaque`, `vie`, `type`, `mode_id`, `description`)
VALUES
  (NOW(),'C\'thun',0,'Légendaire','','Neutre',10,6,6,'Serviteur',@old_gods_id,'Cri de guerre : inflige des dégâts égaux à l''Attaque de ce serviteurs répartis aléatoirement entre tous les adversaires.'),
  (NOW(),'Lardeur, ruine d''Elwynn',0,'Légendaire','','Neutre',7,6,6,'Serviteur',@old_gods_id,'A chaque fois que ce serviteur subit des dégâts, invoque un gnoll 2/2 avec provocation.'),
  (NOW(),'Auspice funeste confirmé',0,'Épique','','Neutre',7,6,6,'Serviteur',@old_gods_id,'	Au début de votre tour, porte l''Attaque de ce serviteur à 7.'),
  (NOW(),'Ver de sable géant',0,'Épique','Bête','Chasseur',8,8,8,'Serviteur',@old_gods_id,'Lorsque ce serviteur attaque un autre serviteur et qu''il le tue, il peut attaquer une fois supplémentaire.'),
  (NOW(),'Mangeur de secrets',0,'Rare','','Neutre',4,2,4,'Serviteur',@old_gods_id,'Cri de guerre : Détruisez tous les secrets de votre adversaire. Gagne +1/+1 pour chaque secret détruit.'),
  (NOW(),'Robot de soins corrompu',0,'Rare','Méca','Neutre',5,6,6,'Serviteur',@old_gods_id,'Râle d''agonie : rend 8 PV au héros adverse.'),
  (NOW(),'Amasseur vicié',0,'Commune','','Neutre',4,4,2,'Serviteur',@old_gods_id,'Rale d''agonie : vous piochez une carte.'),
  (NOW(),'Ancien du crépuscule',0,'Commune','','Neutre',3,3,4,'Serviteur',@old_gods_id,'À la fin de votre tour, donne +1/+1 à votre C''thun (où qu''il soit).'),
  (NOW(),'Annonciatrice du mal',0,'Commune','','Neutre',2,2,3,'Serviteur',@old_gods_id,'Cri de guerre : donne +2/+2 à votre C''thun (où qu''il soit).'),
  (NOW(),'Tenir contre les ténèbres',0,'Commune','','Paladin',5,0,0,'Sort',@old_gods_id,'Invoque cinq recrues de la Main d''argent 1/1.'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description'),
  (NOW(),'name',0,'quality','race','class',7,6,6,'type',@old_gods_id,'description')
;

-- --------------------------------------------------------
SET FOREIGN_KEY_CHECKS=1;