SET FOREIGN_KEY_CHECKS=0;
-- --------------------------------------------------------

ALTER TABLE `@prefix@tab_inventaire` CHANGE `actif` `actif` INT(2) NOT NULL DEFAULT '1';

INSERT INTO `@prefix@tab_mode` (`code`, `label`, `date`) VALUES ('old-gods', 'old-gods', NOW());

SELECT @old_gods_id = a.`id`
  FROM `@prefix@tab_mode` a
  WHERE 1=1
  AND a.`code` = 'old-gods'
;

INSERT INTO `how-tab_inventaire`(`data_creation`, `nom`, `id_link`, `qualite`, `race`, `classe`, `cout`, `attaque`, `vie`, `type`, `mode_id`, `description`)
VALUES
  (NOW(),'C\'thun',0,'Légendaire','','Neutre',10,6,6,'Serviteur',@old_gods_id,'Cri de guerre : inflige des dégâts égaux à l''Attaque de ce serviteurs répartis aléatoirement entre tous les adversaires.'),
  (NOW(),'Lardeur, ruine d''Elwynn',0,'Légendaire','','Neutre',7,6,6,'Serviteur',@old_gods_id,'A chaque fois que ce serviteur subit des dégâts, invoque un gnoll 2/2 avec provocation.'),
  (NOW(),'Auspice funeste confirmé',0,'Épique','','Neutre',5,0,7,'Serviteur',@old_gods_id,'Au début de votre tour, porte l''Attaque de ce serviteur à 7.'),
  (NOW(),'Ver de sable géant',0,'Épique','Bête','Chasseur',8,8,8,'Serviteur',@old_gods_id,'Lorsque ce serviteur attaque un autre serviteur et qu''il le tue, il peut attaquer une fois supplémentaire.'),
  (NOW(),'Mange-secrets',0,'Rare','','Neutre',4,2,4,'Serviteur',@old_gods_id,'Cri de guerre : Détruisez tous les secrets de votre adversaire. Gagne +1/+1 pour chaque secret détruit.'),
  (NOW(),'Robot de soins corrompu',0,'Rare','Méca','Neutre',5,6,6,'Serviteur',@old_gods_id,'Râle d''agonie : rend 8 PV au héros adverse.'),
  (NOW(),'Amasseur vicié',0,'Commune','','Neutre',4,4,2,'Serviteur',@old_gods_id,'Rale d''agonie : vous piochez une carte.'),
  (NOW(),'Ancien du crépuscule',0,'Commune','','Neutre',3,3,4,'Serviteur',@old_gods_id,'À la fin de votre tour, donne +1/+1 à votre C''thun (où qu''il soit).'),
  (NOW(),'Annonciatrice du mal',0,'Commune','','Neutre',2,2,3,'Serviteur',@old_gods_id,'Cri de guerre : donne +2/+2 à votre C''thun (où qu''il soit).'),
  (NOW(),'Résister aux ténèbres',0,'Commune','','Paladin',5,0,0,'Sort',@old_gods_id,'Invoque cinq recrues de la Main d''argent 1/1.'),
  (NOW(),'Tisse-ambre klaxxi',0,'Rare','','Druide',4,4,5,'Serviteur',@old_gods_id,'Cri de guerre : gagne +5 PV si votre C''thun a au moins 10 Attaque.'),
  (NOW(),'Ancienne porte-bouclier',0,'Rare','','Neutre',7,6,6,'Serviteur',@old_gods_id,'Cri de guerre : gagne 10 points d''armure si votre C''thun a au moins 10 Attaque.'),
  (NOW(),'Élue de C''thun',0,'Commune','','Neutre',7,6,6,'Serviteur',@old_gods_id,'Bouclier divin. Cri de guerre : donne +2/+2 à votre C''thun (où qu''il soit.'),
  (NOW(),'Hallazèle l’Elevé',0,'Légendaire','','Chaman',5,4,6,'Serviteur',@old_gods_id,'Chaque fois que vous infligez des dégâts avec un sort, rend autant de points de vie à votre héros.'),
  (NOW(),'Héraut Volazj',0,'Légendaire','','Prêtre',6,5,5,'Serviteur',@old_gods_id,'Cri de guerre : invoque une copie 1/1 de chacun de vos autres serviteurs.'),
  (NOW(),'MALÉDICTION!',0,'Épique','','Démoniste',10,0,0,'Sort',@old_gods_id,'Détruit tous les serviteurs. Proche une carte par serviteur détruit.'),
  (NOW(),'Traînard sans-visage',0,'Épique','','Neutre',4,1,1,'Serviteur',@old_gods_id,'Provocation. Cri de guerre : Copie l''Attaque et la Vie d''un serviteur allié.'),
  (NOW(),'Tentacule de N''Zoth',0,'Commune','','Neutre',1,1,1,'Serviteur',@old_gods_id,'Râle d''agonie : Inflige 1 point de dégât à tous les serviteurs.'),
  (NOW(),'Flamme interdite',0,'Épique','','Mage',0,0,0,'Sort',@old_gods_id,'Dépense tous vos cristaux de mana. Inflige l''équivalent sous forme de dégâts à un serviteur.'),
  (NOW(),'Mutation interdite',0,'Épique','','Prêtre',0,0,0,'Sort',@old_gods_id,'Dépense tous vos cristaux de mana. Invoque un serviteur aléatoire de même coût.'),
  (NOW(),'Soin Interdit',0,'Épique','','Paladin',0,0,0,'Sort',@old_gods_id,'	Dépense tous vos cristaux de mana. Rend deux fois l''équivalent en points de vie.'),
  (NOW(),'Tisse-ambre klaxxi',0,'Rare','','Druide',4,4,5,'Serviteur',@old_gods_id,'Cri de guerre : gagne +5 PV si votre C''thun a au moins 10 Attaque.'),
  (NOW(),'Second de N''Zoth',0,'Commune','Pirate','Guerrier',1,1,1,'Serviteur',@old_gods_id,'Cri de guerre : vous équipe d''un Crochet rouillé 1/3.'),
  (NOW(),'Tauren infesté',0,'Commune','','Neutre',4,2,3,'Serviteur',@old_gods_id,'Provocation. Râle d''agonie : invoque une gelée 2/2.'),
  (NOW(),'N''Zoth le corrupteur',0,'Légendaire','','Neutre',10,5,7,'Serviteur',@old_gods_id,'Cri de guerre : invoque vos serviteurs avec Râle d''agonie morts pendant cette partie.'),
  (NOW(),'Colporteur de Fossoyeuse',0,'Rare','','Voleur',2,2,2,'Serviteur',@old_gods_id,'Râle d''agonie : ajoute une carte aléatoire dans votre main (de la classe de votre adversaire).'),
  (NOW(),'Renoncer aux ténèbres',0,'Épique','','Démoniste',2,0,0,'Sort',@old_gods_id,'Remplace votre pouvoir héroïque et vos cartes Démoniste par ceux d''une autre classe. Les cartes coûtent (1) de moins.'),
  (NOW(),'Rejeton de N''Zoth',0,'Commune','','Neutre',3,2,2,'Serviteur',@old_gods_id,'Râle d''agonie : donne +1/+1 à vos serviteurs.'),
  (NOW(),'L''Épouvantueur',0,'Légendaire','','Neutre',8,6,7,'Serviteur',@old_gods_id,'Quand ce serviteur attaque et détruit un autre serviteur, gagne +2/+2.'),
  (NOW(),'Xaril l''Esprit empoisonné',0,'Légendaire','','Neutre',4,3,2,'Serviteur',@old_gods_id,'Cri de guerre et Râle d''agonie : ajoute une carte Toxine aléatoire dans votre main.'),
  (NOW(),'Tentacules brachiaux',0,'Épique','','Guerrier',5,2,2,'Arme',@old_gods_id,'Râle d''agonie : retourne dans votre main.'),
  (NOW(),'Infester',0,'Rare','','Chasseur',3,0,0,'Sort',@old_gods_id,'Donne à vos serviteurs : "Râle d''agonie : ajoute une carte Bête aléatoire dans votre main."'),
  (NOW(),'Ragnaros, porteur de Lumière',0,'Légendaire','','Paladin',8,8,8,'Serviteur',@old_gods_id,'	À la fin de votre tour, rend 8 points de vie à un personnage allié blessé.'),
  (NOW(),'Apothicaire du culte',0,'Commune','','Neutre',5,4,4,'Serviteur',@old_gods_id,'Cri de guerre : rend 2 PV à votre héros pour chaque serviteur adverse'),
  (NOW(),'Mukla, tyran du val',0,'Légendaire','Bête','Neutre',6,5,5,'Serviteur',@old_gods_id,'Cri de guerre : place 2 bananes dans votre main.'),
  (NOW(),'Dragon de cauchemar',0,'Épique','Dragon','Neutre',7,6,6,'Serviteur',@old_gods_id,'Au début de votre tour, double l''Attaque de ce serviteur.'),
  (NOW(),'Mot de l''ombre : horreur',0,'Rare','','Prêtre',4,0,0,'Sort',@old_gods_id,'Détruit tous les serviteurs avec 2 Attaque ou moins.'),
  (NOW(),'Marque d''Yshaarj',0,'Commune','','Druide',2,0,0,'Sort',@old_gods_id,'Donne +2/+2 à un serviteur. Si c''est une bête, pioche une carte.'),
  (NOW(),'Regisseur de Sombre-Comté',0,'Rare','','Paladin',3,3,3,'Serviteur',@old_gods_id,'	Chaque fois que vous invoquez un serviteur avec 1 PV, lui confère Bouclier divin.'),
  (NOW(),'Sectateur de Skeram',0,'Rare','','Neutre',6,7,6,'Serviteur',@old_gods_id,'Cri de guerre : donne +2/+2 à votre C''thun (où qu''il soit)'),
  (NOW(),'Tome du cabaliste',0,'Épique','','Mage',5,0,0,'Sort',@old_gods_id,'Ajoute 3 sorts de Mage aléatoires dans votre main.'),
  (NOW(),'Y''Shaarj, la rage déchaînée',0,'Légendaire','','Neutre',10,10,10,'Serviteur',@old_gods_id,'À la fin de votre tour, place un serviteur de votre deck sur le champ de bataille.'),
  (NOW(),'Ancien héraut',0,'Épique','','Neutre',6,4,6,'Serviteur',@old_gods_id,'Au début de votre tour, place un serviteur coûtant 10 cristaux de mana de votre deck dans votre main.'),
  (NOW(),'Inquisiteur Aileron noir',0,'Épique','Murloc','Paladin',1,1,3,'Serviteur',@old_gods_id,'Cri de guerre : votre pouvoir héroïque devient « Invoque un murloc 1/1 ».'),
  (NOW(),'Maître de l''évolution',0,'Rare','','Chaman',4,4,5,'Serviteur',@old_gods_id,'Cri de guerre : transforme un serviteur allié en un serviteur aléatoire qui coûte (1) cristal de plus.'),
  (NOW(),'Chose venue d''en bas',0,'Rare','','Chaman',6,5,5,'Serviteur',@old_gods_id,'Provocation. Coûte (1) cristal de moins pour chaque totem que vous avez invoqué pendant cette partie.'),
  (NOW(),'Goule ravageuse',0,'Commune','','Guerrier',3,3,3,'Serviteur',@old_gods_id,'Cri de guerre : Inflige 1 point de dégâts à tous les autres serviteurs.'),
  (NOW(),'Gardien du bourbier',0,'Rare','','class',4,3,3,'Druide',@old_gods_id,'Choix des armes : invoque un limon 2/2 ou confère un cristal de mana vide'),
  (NOW(),'Marteau du crépuscule',0,'Épique','','Chaman',5,4,2,'Arme',@old_gods_id,'Râle d''agonie : invoque un Élémentaire 4/2.'),
  (NOW(),'Sang de l''Ancien',0,'Épique','','Neutre',9,9,9,'Serviteur',@old_gods_id,'Si vous contrôlez deux exemplaires de ce serviteur à la fin de votre tour, les transforme en «  The Ancient One »'),
  (NOW(),'Guerriers de sang',0,'Épique','','Guerrier',3,0,0,'Sort',@old_gods_id,'Place une copie de chaque serviteur allié blessé dans votre main.'),
  (NOW(),'Appel de la nature',0,'Épique','','Chasseur',8,0,0,'Sort',@old_gods_id,'Invoque les 3 compagnons animaux.'),
  (NOW(),'Cho''gall',0,'Légendaire','','Démoniste',7,7,7,'Serviteur',@old_gods_id,'Cri de guerre : le prochain sort que vous jouez pendant ce tour vous coûte des points de vie et non de mana.'),
  (NOW(),'Yogg-Saron, la fin de l''espoir',0,'Légendaire','','Neutre',10,5,7,'Serviteur',@old_gods_id,'Cri de guerre : lance un sort aléatoire pour chaque sort lancé pendant cette partie (cibles choisies au hasard)'),
  (NOW(),'Folie galopante',0,'Rare','','Démoniste',3,0,0,'type',@old_gods_id,'Inflige 9 points de dégâts répartis de façon aléatoire entre TOUS les personnages.'),
  (NOW(),'Villageois possédé',0,'Commune','','Démoniste',1,1,1,'Serviteur',@old_gods_id,'Râle d''agonie : Invoque une Bête d''ombre 1/1.'),
  (NOW(),'Feux follets funestes',0,'Épique','','Druide',7,0,0,'Sort',@old_gods_id,'Choix des armes : Invoque sept feux follets 1/1 ou donne +2/+2 à vos serviteurs.'),
  (NOW(),'Soggoth le Rampant',0,'Légendaire','','Neutre',9,5,9,'Serviteur',@old_gods_id,'Provocation Ne peut pas être la cible de sorts ou de pouvoirs héroïques.'),
  (NOW(),'Invocateur du crépuscule',0,'Épique','','Neutre',4,1,1,'Serviteur',@old_gods_id,'Râle d''agonie: invoque un destructeur sans-visage 5/5'),
  (NOW(),'Thé de chardon',0,'Rare','','Voleur',6,0,0,'Sort',@old_gods_id,'Vous piochez une carte. En place 2 copies supplémentaires dans votre main.'),
  (NOW(),'Étreindre l''ombre',0,'Épique','','Prêtre',2,0,0,'Sort',@old_gods_id,'Vos effets de soins infligent des dégâts pendant ce tour.'),
  (NOW(),'Aile-de-mort, seigneur Dragon',0,'Légendaire','Dragon','Neutre',10,12,12,'Serviteur',@old_gods_id,'Râle d''agonie : place tous les Dragons de votre main sur le champ de bataille.'),
  (NOW(),'Traqueur lugubre',0,'Rare','','Chasseur',3,4,2,'Serviteur',@old_gods_id,'Cri de guerre : donne à vos serviteurs avec Râle d''agonie dans votre main +1/+1.'),
  (NOW(),'Invocateur sans-visage',0,'Commune','','Mage',6,5,5,'Serviteur',@old_gods_id,'Cri de guerre : invoque un serviteur aléatoire coûtant 3 cristaux.'),
  (NOW(),'Serviteur de Yogg-Saron',0,'Rare','','Mage',5,5,4,'Serviteur',@old_gods_id,'Cri de guerre : lance un sort aléatoire coûtant au maximum (5) cristaux de mana (cibles choisies au hasard).'),
  (NOW(),'Exhalombre',0,'Épique','','Voleur',5,4,4,'Serviteur',@old_gods_id,'Cri de guerre : Choisissez un serviteur allié. En place une copie 1/1 qui coûte (1) dans votre main'),
  (NOW(),'Mande-flamme du Crépuscule',0,'Commune','','Mage',3,2,2,'Serviteur',@old_gods_id,'Cri de guerre : inflige 1 point de dégâts à tous les serviteurs adverses.'),
  (NOW(),'Mande-givre dément',0,'Rare','','Mage',4,2,4,'Serviteur',@old_gods_id,'Lorsque vous lancez un sort, gèle un adversaire aléatoire.'),
  (NOW(),'Ombre mouvante',0,'Rare','','Prêtre',4,4,3,'Serviteur',@old_gods_id,'Râle d''agonie : copie une carte du deck adverse et la place dans votre main'),
  (NOW(),'Sombre Arakkoa',0,'Commune','','Druide',6,5,7,'Serviteur',@old_gods_id,'	Provocation. Cri de guerre : donne +3/+3 à votre C''thun (où qu''il soit).'),
  (NOW(),'Princesse Huhuran',0,'Légendaire','Bête','Chasseur',5,6,5,'Serviteur',@old_gods_id,'Cri de guerre : déclenche le Râle d''agonie d''un serviteur allié.'),
  (NOW(),'Déphaseur Zerus',0,'Légendaire','','Neutre',1,1,1,'Serviteur',@old_gods_id,'À chaque tour passé dans votre main, se transforme en un serviteur aléatoire'),
  (NOW(),'Fusion primordiale',0,'Commune','','Chaman',1,0,0,'Sort',@old_gods_id,'Confère +1/+1 à un serviteur pour chacun de vos totems.'),
  (NOW(),'Sans-visage nimbé de flammes',0,'Commune','','Chaman',4,7,7,'Serviteur',@old_gods_id,'Surcharge : (2)'),
  (NOW(),'Sentinelle éternelle',0,'Épique','','Chaman',2,3,2,'Serviteur',@old_gods_id,'Cri de guerre : débloque vos cristaux de mana en surcharge.'),
  (NOW(),'Évolution',0,'Rare','','Chaman',1,0,0,'Sort',@old_gods_id,'Transforme vos serviteurs en serviteurs aléatoires qui coûtent (1) de plus.'),
  (NOW(),'Coup de tonnerre',0,'Commune','','Chaman',2,0,0,'Sort',@old_gods_id,'Inflige 4 points de dégâts à un serviteur. Surcharge : (1)'),
  (NOW(),'Loup contaminé',0,'Rare','Bête','Chasseur',4,3,3,'Serviteur',@old_gods_id,'Râle d''agonie : invoque 2 araignées 1/1.'),
  (NOW(),'Chauve-souris embrasée',0,'Commune','Bête','Chasseur',1,2,1,'Serviteur',@old_gods_id,'Râle d''agonie : inflige 1 point de dégâts à un adversaire aléatoire.'),
  (NOW(),'En chasse',0,'Commune','','Chasseur',1,0,0,'Sort',@old_gods_id,'Inflige 1 point de dégâts. Invoque un Mastiff 1/1.'),
  (NOW(),'Larve putride',0,'Commune','Bête','Chasseur',3,2,5,'Serviteur',@old_gods_id,''),
  (NOW(),'Rituel interdit',0,'Épique','','Démoniste',0,0,0,'Sort',@old_gods_id,'Dépense tous vos cristaux de mana. Invoque un nombre équivalent de tentacules 1/1.'),
  (NOW(),'Passeuse d''âmes',0,'Commune','','Démoniste',5,5,6,'Serviteur',@old_gods_id,'Chaque fois qu''un serviteur allié meurt, donne +1/+1 à votre C''thun (où qu''il soit)'),
  (NOW(),'Conseiller de Sombre-Comté',0,'Commune','','Démoniste',3,1,5,'Serviteur',@old_gods_id,'Après que vous avez invoqué un serviteur, gagne +1 d''Attaque.'),
  (NOW(),'Archiviste de Sombre-Comté',0,'Rare','','Démoniste',2,3,2,'Serviteur',@old_gods_id,'Cri de guerre : vous défausse d''une carte au hasard.Râle d''agonie : pioche une carte.'),
  (NOW(),'Fandral Forteramure',0,'Légendaire','','Druide',4,3,5,'Serviteur',@old_gods_id,'Vos cartes avec Choix des armes ont leurs deux effets combinés.'),
  (NOW(),'Grizzly perturbé',0,'Rare','Bête','Druide',3,2,2,'Serviteur',@old_gods_id,'Après que vous avez invoqué un serviteur, lui confère +1/+1.'),
  (NOW(),'Ancien frappé d''interdit',0,'Épique','','Druide',1,1,1,'Serviteur',@old_gods_id,'Cri de guerre : dépense tous vos cristaux de mana. Gagne +1/+1 pour chaque cristal dépensé.'),
  (NOW(),'Rage farouche',0,'Commune','','Druide',3,0,0,'Sort',@old_gods_id,'Choix des armes - donne à votre héros +4 Attaque pendant ce tour ou confère +8 Armure.'),
  (NOW(),'Malkorok',0,'Légendaire','','Guerrier',7,6,5,'Serviteur',@old_gods_id,'Cri de guerre : vous équipe d''une arme aléatoire.'),
  (NOW(),'Adepte de la Voile sanglante',0,'Rare','Pirate','Guerrier',3,3,4,'Serviteur',@old_gods_id,'Cri de guerre : si vous contrôlez un pirate, donne +1/+1 à votre arme.'),
  (NOW(),'Brave Sabot-de-sang',0,'Commune','','Guerrier',4,2,6,'Serviteur',@old_gods_id,'Provocation, Accès de rage : +3 Attaque.'),
  (NOW(),'Du sang à l''ichor',0,'Rare','','Guerrier',1,0,0,'Sort',@old_gods_id,'Inflige 1 point de dégâts à un serviteur. S''il survit, invoque une gelée 2/2.'),
  (NOW(),'Anomalus',0,'Légendaire','','Mage',8,8,6,'Serviteur',@old_gods_id,'Râle d''agonie : inflige 8 points de dégâts à tous les serviteurs.'),
  (NOW(),'Ensorceleuse du culte',0,'Rare','','Mage',2,3,2,'Serviteur',@old_gods_id,'Dégâts des sorts : +1. Après que vous avez lancé un sort, confère +1/+1 à votre C''thun (où qu''il soit)'),
  (NOW(),'Fracasser',0,'Commune','','Mage',2,0,0,'Sort',@old_gods_id,'Détruit un serviteur gelé.'),
  (NOW(),'Lame de ralliement',0,'Rare','','Paladin',3,3,2,'Arme',@old_gods_id,'Cri de guerre : confère +1/+1 à vos serviteurs avec Bouclier divin'),
  (NOW(),'Héroïne altruiste',0,'Rare','','Paladin',7,6,6,'Serviteur',@old_gods_id,'Râle d''agonie : confère Bouclier divin à un serviteur allié aléatoire.'),
  (NOW(),'Lumière dans les ténèbres',0,'Commune','','Paladin',2,0,0,'Sort',@old_gods_id,'Découvre un serviteur. Lui donne +1/+1.'),
  (NOW(),'Force divine',0,'Commune','','Paladin',1,0,0,'Sort',@old_gods_id,'Confère +1/+2 à un serviteur.'),
  (NOW(),'Soingeuse du crépuscule',0,'Rare','','Prêtre',5,6,5,'Serviteur',@old_gods_id,'Cri de guerre : rend 10 PV à votre héros si votre C''thun a au moins 10 Attaque.'),
  (NOW(),'Acolyte capuchonnée',0,'Commune','','Prêtre',7,6,6,'Serviteur',@old_gods_id,'À chaque fois qu''un personnage est soigné, donne +1/+1 à votre C''thun (où qu''il soit)'),
  (NOW(),'Alchimiste de Sombre-Comté',0,'Commune','','Prêtre',5,4,5,'Serviteur',@old_gods_id,'Cri de guerre : rend 5 PV.'),
  (NOW(),'Mot de pouvoir : tentacules',0,'Commune','','Prêtre',5,0,0,'Sort',@old_gods_id,'Donne +2/+6 à un serviteur.'),
  (NOW(),'Lame de C''thun',0,'Épique','','Voleur',9,4,4,'Serviteur',@old_gods_id,'Cri de guerre : détruit un serviteur. Ajoute son Attaque et sa Vie à C''thun (Où qu''il soit)'),
  (NOW(),'Sectateur de la Lame',0,'Commune','','Voleur',1,1,2,'Serviteur',@old_gods_id,'Combo : gagne +1/+1.'),
  (NOW(),'Face de poulpe',0,'Commune','Pirate','Voleur',4,4,4,'Serviteur',@old_gods_id,'Râle d''agonie : donne +2 ATQ à votre arme.'),
  (NOW(),'Attaque d''ombre',0,'Commune','','Voleur',3,0,0,'Sort',@old_gods_id,'Inflige 5 points de dégâts à un personnage indemne.'),
  (NOW(),'Périple dans les abîmes',0,'Rare','','Voleur',1,0,0,'Sort',@old_gods_id,'Découvre une carte avec Râle d''agonie'),
  (NOW(),'Empereur jumeau Vek''lor',0,'Légendaire','','Neutre',7,6,6,'Serviteur',@old_gods_id,'Provocation. Cri de guerre : invoque un autre empereur si votre C''thun a au moins 10 Attaque.'),
  (NOW(),'Nat le sombre pêcheur',0,'Légendaire','','Neutre',2,2,4,'Serviteur',@old_gods_id,'Au début de son tour, votre adversaire a 50% de chances de piocher une carte supplémentaire.'),
  (NOW(),'Adorateur fanatisé',0,'Épique','','Neutre',5,3,6,'Serviteur',@old_gods_id,'Provocation. Quand ce serviteur subit des dégâts, donne +1/+1 à votre C''thun (où qu''il soit)'),
  (NOW(),'Sombre orateur',0,'Épique','','Neutre',5,3,6,'Serviteur',@old_gods_id,'Cri de guerre : échange ses caractéristiques avec un serviteur allié.'),
  (NOW(),'Horreur cyclopéenne',0,'Épique','','Neutre',4,3,3,'Serviteur',@old_gods_id,'Provocation. Cri de guerre : gagne +1 PV pour chaque serviteur adverse.'),
  (NOW(),'Pirate des flots noirs',0,'Rare','Pirate','Neutre',4,2,5,'Serviteur',@old_gods_id,'Vos armes coûtent (2) de moins.'),
  (NOW(),'Implorateur funeste',0,'Rare','','Neutre',8,7,9,'Serviteur',@old_gods_id,'Cri de guerre : confère à votre C''thun +2/+2 (où qu''il soit). S''il est mort, le place à votre deck.'),
  (NOW(),'Disciple de C''thun',0,'Rare','','Neutre',3,2,1,'Serviteur',@old_gods_id,'Cri de guerre : inflige 2 points de dégâts. Donne +2/+2 à votre C''thun (où qu''il soit)'),
  (NOW(),'Grouillant silithide',0,'Rare','','Neutre',3,3,5,'Serviteur',@old_gods_id,'Ne peut attaquer que si votre héros a attaqué pendant ce tour.'),
  (NOW(),'Voyant corrompu',0,'Rare','Murloc','Neutre',6,2,3,'Serviteur',@old_gods_id,'Cri de guerre : inflige 2 points de dégâts à tous les serviteurs non murlocs.'),
  (NOW(),'Drake de minuit',0,'Rare','Dragon','Neutre',4,1,4,'Serviteur',@old_gods_id,'Cri de guerre : gagne +1 ATQ pour chaque autre carte dans votre main.'),
  (NOW(),'Tentacule remuant',0,'Commune','','Neutre',3,2,4,'Serviteur',@old_gods_id,'Provocation'),
  (NOW(),'Géomancienne du crépuscule',0,'Commune','','Neutre',2,1,4,'Serviteur',@old_gods_id,'Provocation.Cri de guerre : donne Provocation à votre C''thun (où qu''il soit).'),
  (NOW(),'Murloc aileron-bilieux',0,'Commune','Murloc','Neutre',2,2,1,'Serviteur',@old_gods_id,'Cri de guerre : invoque un limon 1/1 avec Provocation'),
  (NOW(),'Psych-o-tron',0,'Commune','Méca','Neutre',5,3,4,'Serviteur',@old_gods_id,'Provocation. Bouclier divin'),
  (NOW(),'Initié zélé',0,'Commune','race','Neutre',1,1,1,'Serviteur',@old_gods_id,'Râle d''agonie : confère +1/+1 à un serviteur allié aléatoire.'),
  (NOW(),'Worgen corrompu',0,'Commune','','Neutre',2,3,1,'Serviteur',@old_gods_id,'Camouflage'),
  (NOW(),'Prophète nérubien',0,'Commune','','Neutre',6,4,4,'Serviteur',@old_gods_id,'Au début de votre tour, réduit le coût en mana de cette carte de (1) cristal.'),
  (NOW(),'Berserker aberrant',0,'Commune','','Neutre',4,3,5,'Serviteur',@old_gods_id,'Accès de rage : +2 Attaque'),
  (NOW(),'Enragé am''gam',0,'Commune','','Neutre',3,1,5,'Serviteur',@old_gods_id,''),
  (NOW(),'Rampant des marais',0,'Commune','','Neutre',7,6,8,'Serviteur',@old_gods_id,'Provocation'),
  (NOW(),'Sangler de pénombre',0,'Commune','Bête','Neutre',2,4,1,'Serviteur',@old_gods_id,''),
  (NOW(),'Horreur indiscible',0,'Commune','','Neutre',8,6,10,'Serviteur',@old_gods_id,''),
  (NOW(),'Kobold évolué',0,'Commune','','Neutre',4,2,2,'Serviteur',@old_gods_id,'Dégâts des sorts : +2.'),
  (NOW(),'Béhémoth Sans-visage',0,'Commune','','Neutre',10,10,10,'Serviteur',@old_gods_id,''),
  (NOW(),'Faucon-dragon difforme',0,'Commune','Bête','Neutre',7,5,5,'Serviteur',@old_gods_id,'Furie-des-vents')
;

-- --------------------------------------------------------
SET FOREIGN_KEY_CHECKS=1;